# Numpy

In [2]:
import numpy as np

- When you feel the need for more dimensions

In [3]:
oneDimArray = np.zeros((5))
twoDimArray = np.ones((5,5))
threeDimArray = np.random.randint(low = 0, high = 10, size = (5,5,5))

In [4]:
print(oneDimArray)
print('-')
print(twoDimArray)
print('-')
print(threeDimArray)

[0. 0. 0. 0. 0.]
-
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
-
[[[6 0 3 8 2]
  [1 4 4 9 5]
  [0 4 7 8 0]
  [7 2 7 7 3]
  [3 9 2 4 4]]

 [[6 8 8 9 4]
  [0 6 2 5 0]
  [2 2 6 7 1]
  [5 6 7 4 8]
  [6 1 2 3 0]]

 [[5 8 1 1 7]
  [5 6 3 3 8]
  [6 9 9 7 2]
  [4 2 3 4 8]
  [2 5 6 0 1]]

 [[1 5 0 5 6]
  [4 5 5 7 2]
  [7 3 4 5 2]
  [8 1 9 6 1]
  [4 1 3 5 9]]

 [[7 8 6 7 6]
  [5 6 7 6 5]
  [2 1 7 2 0]
  [1 2 6 3 3]
  [5 2 9 2 1]]]


In [5]:
print(threeDimArray.shape)
print(threeDimArray.ndim)
print(threeDimArray.size)

(5, 5, 5)
3
125


In [6]:
threeDimArray[0]

array([[6, 0, 3, 8, 2],
       [1, 4, 4, 9, 5],
       [0, 4, 7, 8, 0],
       [7, 2, 7, 7, 3],
       [3, 9, 2, 4, 4]])

In [7]:
threeDimArray[0][0] = "8"

In [8]:
threeDimArray[0]

array([[8, 8, 8, 8, 8],
       [1, 4, 4, 9, 5],
       [0, 4, 7, 8, 0],
       [7, 2, 7, 7, 3],
       [3, 9, 2, 4, 4]])

In [9]:
threeDimArray[:,:,-1]

array([[8, 5, 0, 3, 4],
       [4, 0, 1, 8, 0],
       [7, 8, 2, 8, 1],
       [6, 2, 2, 1, 9],
       [6, 5, 0, 3, 1]])

In [10]:
oneDimArray[0] = "Test"

ValueError: could not convert string to float: 'Test'