# Numpy

In [3]:
import numpy as np

- When you feel the need for more dimensions

In [34]:
oneDimArray = np.zeros((5))
twoDimArray = np.ones((5,5))
threeDimArray = np.random.randint(low = 0, high = 10, size = (5,5,5))

In [25]:
print(oneDimArray)
print('-')
print(twoDimArray)
print('-')
print(threeDimArray)

[0. 0. 0. 0. 0.]
-
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
-
[[[7 8 9 4 3]
  [7 7 9 4 7]
  [0 1 5 1 4]
  [1 0 2 7 0]
  [9 2 7 8 2]]

 [[9 8 4 4 2]
  [2 1 1 7 8]
  [8 8 7 0 5]
  [8 0 3 6 0]
  [6 7 6 7 6]]

 [[7 2 0 5 2]
  [3 4 0 7 6]
  [4 7 4 4 2]
  [5 0 3 5 5]
  [7 4 5 9 3]]

 [[3 0 7 0 2]
  [4 5 5 9 9]
  [4 6 5 8 4]
  [9 3 3 7 1]
  [3 9 5 2 3]]

 [[7 9 0 8 8]
  [9 3 8 2 4]
  [6 4 1 7 7]
  [8 7 4 5 5]
  [6 4 6 6 9]]]


In [28]:
print(threeDimArray.shape)
print(threeDimArray.ndim)
print(threeDimArray.size)

(5, 5, 5)
3
125


In [40]:
threeDimArray[0]

array([[8, 8, 8, 8, 8],
       [5, 3, 9, 4, 3],
       [9, 8, 6, 5, 0],
       [6, 0, 3, 2, 8],
       [3, 1, 3, 2, 3]])

In [38]:
threeDimArray[0][0] = "8"

In [39]:
threeDimArray[0]

array([[8, 8, 8, 8, 8],
       [5, 3, 9, 4, 3],
       [9, 8, 6, 5, 0],
       [6, 0, 3, 2, 8],
       [3, 1, 3, 2, 3]])

In [42]:
threeDimArray[:,:,-1]

array([[8, 3, 0, 8, 3],
       [1, 9, 1, 5, 2],
       [0, 0, 9, 7, 4],
       [9, 6, 1, 2, 3],
       [0, 4, 9, 4, 1]])